job_scraper/urls.py
from django.urls import path, re_path
from . import views
from django.views.generic.base import RedirectView


app_name = 'job_scraper'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('search', views.IndexView.as_view(), name='index'),
    path('companies', views.CompanyIndexView.as_view(template_name='companies.html')),
    path('locations', views.LocationIndexView.as_view(template_name='locations.html')),
    path('tags', views.TagIndexView.as_view(template_name='tags.html')),
    path('job/apply-to-<int:pk>/<slug:slug>', views.ApplyView.as_view(), name='apply'),
    path('job/<int:pk>/<slug:slug>', views.DetailView.as_view(), name='detail'),
]

webapp/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf import settings
from django.views.static import serve
from django.conf.urls import url, include
from django.views.generic.base import TemplateView
from django.shortcuts import render
from job_scraper import views

urlpatterns = [
    url(r'', include('webmaster_verification.urls')),
    path('admin/', admin.site.urls),
    path('about/cookiepolicy', TemplateView.as_view(template_name='cookiepolicy.html')),
    path('about/about-us', TemplateView.as_view(template_name='about.html')),
    path('about/contact-us', views.ContactFormView.as_view()),
    path('donations', TemplateView.as_view(template_name='payment_process.html')),
    re_path(r'jobs-in-\w+', views.IndexView.as_view(), name='index'),
    re_path(r'tags-in-\w+', views.TagIndexView.as_view(), name='tags.html'),
    re_path(r'jobs-at-\w+', views.IndexView.as_view(), name='index'),
    re_path(r'(.*?)-jobs', views.IndexView.as_view(), name='index'),
    path('', include('job_scraper.urls')),
    # path('api/jobs/', views.JobListApiView.as_view()),
    # path('api/jobs/<int:pk>/', views.JobDetailApiView.as_view()),
]


def handler404(request, exception, template_name="404.html"):
    response = render(request, template_name)
    response.status_code = 404
    return response


if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

job_scraper/forms.py
from django import forms
from django.core.mail import get_connection, send_mail
from django.conf import settings


class ContactForm(forms.Form):

    name = forms.CharField(error_messages={'required': 'Please define a value for Name field'})
    email = forms.EmailField(error_messages={'required': 'Please define a value for Email field'})
    message = forms.CharField(error_messages={'required': 'Please define a Message'})

    def send_email(self):
        with get_connection(
                host=settings.EMAIL_HOST,
                port=settings.EMAIL_PORT,
                username=settings.EMAIL_FEEDBACK_USER,
                password=settings.EMAIL_FEEDBACK_PASSWORD,
                use_tls=settings.EMAIL_USE_TLS
        ) as connection:
            send_mail(
                self.data["name"] + " \t " + self.data["email"],
                self.data["message"],
                settings.EMAIL_FEEDBACK_USER,
                settings.EMAIL_RECIPIENT_LIST,
                connection=connection,
                fail_silently=False,
            )

job_scraper/views.py
from rest_framework import generics
from django.views import generic
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.db.models import Q, Count
from django.views.generic.edit import FormView
from django.conf import settings
from django.contrib import messages
from re import escape
from re import search
from urllib.parse import unquote
from datetime import datetime, date

from operator import and_
from operator import or_
import functools
import requests
from collections import OrderedDict
from itertools import chain

from .forms import ContactForm
from job_scraper.models import Job
from job_scraper.models import Company
from job_scraper.models import UserSearches
from job_scraper.models import City
from job_scraper.models import Tag
from job_scraper.serializers import JobSerializer, JobDetailSerializer


class ContactFormView(FormView):
    template_name = 'contact.html'
    form_class = ContactForm

    def form_valid(self, form):
        # reCAPTCHA validation
        recaptcha_response = self.request.POST.get('g-recaptcha-response')
        data = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            'response': recaptcha_response
        }
        r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
        result = r.json()
        if result['success']:
            form.send_email()
        else:
            form.add_error(None, "Invalid reCAPTCHA. Please try again.")
            return super().form_invalid(form)

        messages.success(self.request, 'Message has been sent successfully! Thank you!')
        return self.render_to_response(self.get_context_data(form=form))

    def form_invalid(self, form):
        return super().form_invalid(form)


class IndexView(generic.ListView):
    template_name = 'index.html'
    paginate_by = 20
    context_object_name = 'jobs_list'
    only_english = None
    company = None
    location_text = None
    company_text = None
    keyword_text = None

    def get_context_data(self, **kwargs):
        ctx = super(IndexView, self).get_context_data(**kwargs)
        ctx['company'] = self.company
        if self.company:
            ctx["company_text"] = self.company.name

        if 'location' in self.request.GET:
            ctx['location_text'] = self.request.GET['location'].capitalize()

        if 'keyword' in self.request.GET:
            ctx['keyword_text'] = self.request.GET['keyword'].capitalize()

        return ctx

    @staticmethod
    def filter_by_location(location_query):
        # Gets those active jobs for a specific location when the end_date is either greater than today or end_date is None
        today = datetime.today()
        if only_english and only_english == "on":
            return Q(is_active=True, end_date__gte=today, language="en", cities__name__iexact=location_query) | Q(is_active=True, end_date=None, language="en", cities__name__iexact=location_query) |\
                   Q(is_active=True, end_date__gte=today, language="en", cities__region__name__iexact=location_query) | Q(is_active=True, end_date=None, language="en", cities__region__name__iexact=location_query)
        else:
            return Q(is_active=True, end_date__gte=today, cities__name__iexact=location_query) | Q(is_active=True, end_date=None, cities__name__iexact=location_query) |\
                   Q(is_active=True, end_date__gte=today, cities__region__name__iexact=location_query) | Q(is_active=True, end_date=None, cities__region__name__iexact=location_query)

    @staticmethod
    def filter_by_active():
        # Gets those active jobs when the end_date is either greater than today or end_date is None
        today = datetime.today()
        if only_english and only_english == "on":
            return Q(is_active=True, end_date__gte=today, language="en") | Q(is_active=True, end_date=None, language="en")
        else:
            return Q(is_active=True, end_date__gte=today) | Q(is_active=True, end_date=None)

    def get_queryset(self):
        keyword_query = self.request.GET.get('keyword', None)
        location_query = self.request.GET.get('location', None)
        global only_english
        only_english = self.request.GET.get('only_english', "None")

        # checks URLS like '/python-jobs-in-Tampere'
        m = search(r"^/(.+?)-jobs-in-(.+?)$", self.request.path)
        if m and m.group(1) and m.group(2):
            keyword_query = m.group(1)
            self.request.GET._mutable = True
            self.request.GET["keyword"] = keyword_query
            if not Tag.is_valid_tag(keyword_query):
                raise Http404

            location_query = m.group(2)
            self.request.GET._mutable = True
            self.request.GET["location"] = location_query
            if not City.is_valid_location(location_query):
                raise Http404
        else:
            if self.request.get_full_path().startswith("/jobs-in-"):
                location_query = self.request.path.split("/jobs-in-")[1]
                self.request.GET._mutable = True
                self.request.GET["location"] = location_query
                if not City.is_valid_location(location_query):
                    raise Http404

            if self.request.get_full_path().startswith("/jobs-at-"):
                keyword_query_raw = self.request.path.split("/jobs-at-")[1]
                keyword_query = unquote(keyword_query_raw)
                self.request.GET._mutable = True
                self.request.GET["keyword"] = keyword_query

            if self.request.get_full_path().endswith("-jobs"):
                keyword_query_raw = self.request.path.split("-jobs")[0]
                # remove initial "/"
                keyword_query = unquote(keyword_query_raw[1:])
                self.request.GET._mutable = True
                self.request.GET["keyword"] = keyword_query
                if not Tag.is_valid_tag(keyword_query):
                    raise Http404

        if keyword_query and location_query:
            keyword_words = keyword_query.split(" ")

            # If the search has special characters, the word boundary '\y' is not valid, we need to remove it in order to return the proper jobs.
            if search("[^a-zA-Z0-9 ]+", keyword_query):
                # It returns all jobs which title contains all words typed by the user. In any order
                list1 = Job.objects.filter(functools.reduce(and_, [Q(title__iregex=r"\y" + escape(q)) | Q(company__name__iregex=r"\y" + escape(q)) for q in keyword_words]) & self.filter_by_location(location_query)).order_by('-is_highlighted', '-updated_at')

            else:
                list1 = Job.objects.filter(functools.reduce(and_, [Q(title__iregex=escape(q) + r"\y") | Q(company__name__iregex=r"\y" + escape(q) + r"\y") for q in keyword_words]) & self.filter_by_location(location_query)).order_by('-is_highlighted', '-updated_at')

            # Gets jobs which full query matches with a keyword
            list2 = Job.objects.filter(functools.reduce(or_, [Q(tags__name__iexact=keyword_query)]) & self.filter_by_location(location_query)).order_by('-is_highlighted', '-jobtagmap__num_times')

            # Gets jobs which any word from user query matches with a keyword
            list3 = Job.objects.filter(functools.reduce(or_, [Q(tags__name__iexact=q) for q in keyword_words]) & self.filter_by_location(location_query)).order_by('-is_highlighted', '-jobtagmap__num_times')

            result_list = list(chain(list1, list2, list3))

            UserSearches.add_entry(what_entry=keyword_query, where_entry=location_query)
            return list(OrderedDict.fromkeys(result_list))

        if keyword_query:
            try:
                self.company = Company.objects.get(name__iexact=keyword_query)
                if self.company:
                    return Job.objects.filter(Q(company__name__iexact=keyword_query) & self.filter_by_active()).order_by('-is_highlighted', '-updated_at')
            except (Company.DoesNotExist, Company.MultipleObjectsReturned):
                pass

            keyword_words = keyword_query.split(" ")

            # If the search has special characters, the word boundary '\y' is not valid, we need to remove it in order to return the proper jobs.
            if search("[^a-zA-Z0-9 ]+", keyword_query):
                list1 = Job.objects.filter(functools.reduce(and_, [Q(title__iregex=escape(q)) | Q(company__name__iregex=escape(q)) for q in keyword_words]) & self.filter_by_active()).order_by('-is_highlighted', '-updated_at')
            else:
                list1 = Job.objects.filter(functools.reduce(and_, [Q(title__iregex=r"\y" + escape(q) + r"\y") | Q(company__name__iregex=r"\y" + escape(q) + r"\y") for q in keyword_words]) & self.filter_by_active()).order_by('-is_highlighted', '-updated_at')

            # Gets jobs which full query matches with a keyword
            list2 = Job.objects.filter(functools.reduce(or_, [Q(tags__name__iexact=keyword_query)]) & self.filter_by_active()).order_by('-is_highlighted', '-jobtagmap__num_times')

            # Gets jobs which any word from user query matches with a keyword
            list3 = Job.objects.filter(functools.reduce(or_, [Q(tags__name__iexact=q) for q in keyword_words]) & self.filter_by_active()).order_by('-is_highlighted', '-jobtagmap__num_times')

            result_list = list(chain(list1, list2, list3))

            UserSearches.add_entry(what_entry=keyword_query)
            return list(OrderedDict.fromkeys(result_list))

        if location_query:
            UserSearches.add_entry(where_entry=location_query)
            return Job.objects.filter(self.filter_by_location(location_query)).order_by('-is_highlighted', '-updated_at')
        else:
            return Job.objects.filter(self.filter_by_active()).order_by('-is_highlighted', '-updated_at')


class DetailView(generic.DetailView):
    model = Job
    template_name = 'detail.html'
    is_disable = False

job_scraper/templates/about.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="row justify-content-center ">
        <div class="col-12 col-11">
            <div class="row mt-5">
                <div class="col text-center">
                    <h1><strong>About us</strong></h1>
                </div>
            </div>
            <div class="row">
                <div class="col mt-4 mb-lg-5">
                    <p>
                        <a href="/" class="about-links about-style-link">JobsPortal.fi</a>
                        was made to help people interested about the jobs market from Finland.
                    </p>
                    <p>
                        Based on personal experience, for a person is not easy to find the open jobs available at a certain time. Also, companies that are interested to fill in certain open positions
                        they
                        have, sometimes struggle to get the exposure they want.
                    </p>
                    <p>
                        As it can be seen above, the website is mainly targeting people who are looking for a job, or interested about what opportunities are available.
                        However, companies can also benefit from our website, by getting bigger exposure to potential candidates.
                    </p>
                    <p>
                        Recruiters may also be interested in utilising our website, getting access to certain metrics, to allow them to find out easier what companies may benefit the most from their
                        expertise. More on recruiters later on, when we have enough relevant data.
                    </p>
                    <p>
                        At this point, we are working on adding more companies to the website and to enhance the user experience, therefore more insights will be revealed as we can showcase the
                        features.
                    </p>
                    <p>
                        If you have suggestions, or bugs to report, please don't hesitate to get in touch through our <a href="/about/contact-us" class="about-links about-style-link">Contact us</a>
                        section.
                    </p>
                    <p>
                        Thank you for passing by and we hope to "see" you again.
                    </p>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

job_scraper/templates/companies.html
{% extends "base.html" %}
{% load static %}
{% load search_tags %}


{% block content %}
    <div class="row mt-5 mb-4">
        <div class="col text-center">
            <h4>
                <strong>
                    Wondering what companies we already cover? Here are all of them!
                </strong>
            </h4>
        </div>
    </div>

    <div class="row justify-content-center align-items-center">
        {% for company in companies_list %}
            {% if forloop.counter0|divisibleby:6 %}
                </div><br>
                <div class="row justify-content-center align-items-center">
            {% endif %}

            <div class="col-4 col-lg-2 text-center mt-3 mt-lg-0">
                <a href="/jobs-at-{{ company.name }}"><img class="zoom hoverable logos" src="{{ company.logo100.url }}" alt="{{ company.name }}"></a>
            </div>
        {% endfor %}

        </div>

    <div class="row mt-5">
        <div class="col mt-5 mb-5">
            <h5>
                <strong>
                    Are you representing a company that has open jobs in Finland? <a href="/about/contact-us" class="about-links about-style-link">Let us know</a> and we will for sure include you in
                    our list, as soon as time allows us!
                </strong>
            </h5>
        </div>
    </div>

    <div>
        <button onclick="topFunction()" id="myBtn" title="Go to top"><img src="{% static 'images/arrow_up.png' %}" alt="" class="arrow-size"></button>
    </div>

{% endblock %}

job_scraper/templates/contact.html
{% extends "base.html" %}

{% load static %}


{% block content %}

    <div class="row justify-content-center mt-5">
        <h1>
            <strong>
                Contact us
            </strong>
        </h1>
    </div>
    <div class="row justify-content-center mt-3">
        <div class="col col-lg-11">
            <p>
                We welcome feedback from our visitors! </p>
            <p>
                If you have a suggestion, found a bug or simply want to say hello, please feel free to contact us by using the form below.
            </p>
        </div>
    </div>

    {% if messages %}
        {% for message in messages %}
            <div class="success-form-height">
                <div class="row justify-content-center mt-3">
                    <div class="col-5 col-lg-2 justify-content-center align-self-center">
                        <div class="check_mark">
                            <div class="sa-icon sa-success animate">
                                <span class="sa-line sa-tip animateSuccessTip"></span>
                                <span class="sa-line sa-long animateSuccessLong"></span>
                                <div class="sa-placeholder"></div>
                                <div class="sa-fix"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-lg-8 text-center text-lg-left justify-content-center align-self-center mb-lg-4">
                        <div class="success-message">
                            {{ message }}
                        </div>
                    </div>
                </div>

                <div class="row justify-content-center">
                    <div class="col text-center pt-5 pt-lg-0">
                        <p><strong>
                            Please continue to browse our current open <a href="/" class="about-style-link">jobs</a>
                        </strong>
                        </p>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class="row justify-content-center mt-3 ">
            <div class="col-12 col-lg-10">
                <form method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-12 col-lg-6 ">
                            <div class="row ">
                                <div class="col-3 col-lg-3 text-right pl-lg-5 pt-2">
                                    <label for="{{ form.name.id_for_label }}"><strong>Name</strong></label>
                                </div>
                                <div class="col-9 col-lg-9 pl-1">
                                    <input type="text"
                                           class="form-control"
                                           name="{{ form.name.name }}"
                                           id="{{ form.name.id_for_label }}"
                                            {% if form.name.value != None %} value="{{ form.name.value|stringformat:'s' }}" {% endif %}
                                           maxlength="{{ form.name.field.max_length }}">
                                </div>
                            </div>
                            {% if form.name.errors %}
                                <div class="row ml-5">
                                    <div class="field-error mt-1">
                                        {{ form.name.errors }}
                                    </div>
                                </div>
                            {% endif %}
                        </div>

                        <div class="col-12 col-lg-6">
                            <div class="row mt-3 mt-lg-0 ">
                                <div class="col-3 col-lg-3 text-right pl-lg-5 pt-2">
                                    <label for="{{ form.email.id_for_label }}"><strong>Email</strong></label>
                                </div>
                                <div class="col-9 col-lg-9 pl-1">
                                    <input type="text"
                                           class="form-control"
                                           name="{{ form.email.name }}"
                                           id="{{ form.email.id_for_label }}"
                                           {% if form.email.value != None %}value="{{ form.email.value|stringformat:'s' }}"{% endif %}
                                           maxlength="{{ form.email.field.max_length }}">
                                </div>
                            </div>
                            {% if form.email.errors %}
                                <div class="row ml-5">
                                    <div class="field-error mt-1">
                                        {{ form.email.errors }}
                                    </div>
                                </div>
                            {% endif %}
                        </div>

                    </div>

                    <div class="row mt-3">
                        <div class="col-12 col-lg-6">
                            <div class="row">
                                <div class="col-3 col-lg-3 text-right pl-lg-4 pt-2">
                                    <label for="{{ form.message.id_for_label }}"><strong>Message</strong></label>
                                </div>
                                <div class="col-9 col-lg-9 pl-1">
                                <textarea type="text" class="form-control" rows="7" name="{{ form.message.name }}" id="{{ form.message.id_for_label }}" maxlength="{{ form.message.field.max_length }}">{% if form.message.value != None %}{{ form.message.value|stringformat:'s' }} {% endif %}</textarea>
                                </div>
                            </div>
                            {% if form.message.errors %}
                                <div class="row ml-5">
                                    <div class="field-error mt-1">
                                        {{ form.message.errors }}
                                    </div>
                                </div>
                            {% endif %}
                        </div>

                        <div class="col-12 col-lg-5 ml-5 pl-lg-5 mt-3">
                            <div class="row">
                                <div class="g-recaptcha" data-sitekey="6LcuMZAUAAAAAC9m70-YknHwHPL05MdlRtn2YhBG"></div>
                                {% if form.non_field_errors %}
                                    <div class="row">
                                        <div class="field-error mt-1">
                                            {{ form.non_field_errors }}
                                        </div>
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                    </div>


                    <div class="row justify-content-center">
                        <div class="col-4 col-lg-2 mt-5 mb-lg-5">
                            <button id="search_button" type="submit" class="btn btn-primary">Send!</button>
                        </div>
                    </div>
                </form>


            </div>

        </div>
    {% endif %}
{% endblock %}

job_scraper/templates/detail.html
{% extends "base.html" %}
{% load static %}

{% block keywords %}{{ job.get_meta_keywords }}{% endblock %}
{% block title %}{{ job.title }} • Jobs Portal {% endblock %}


{% block content %}

    {% if is_disabled %}
        <div class="alert alert-danger alert-danger-border mt-5 mb-5" role="alert">
            <div class="row pt-2 pb-2">
                <div class="col text-center font-weight-bold">
                    <h4>This job is no longer active. It was disabled the {{ job.get_updated_date }} by {{ job.company}}</h4>
                </div>
            </div>

        </div>
    {% elif is_expired %}
        <div class="alert alert-danger alert-danger-border mt-5 mb-5" role="alert">
            <div class="row pt-2 pb-2">
                <div class="col text-center font-weight-bold">
                    <h4>This job is no longer active. It expired the {{ job.end_date }}</h4>
                </div>
            </div>

        </div>
    {% endif %}

    <div class="row mt-3">
        <div class="col text-md-center">
            <h1><strong>{{ job.title }}</strong></h1>
        </div>
    </div>

    <div class="row row-details mt-2 ml-md-1">
        <div class="col">
            <div class="row d-flex align-items-center h-100">
                <div class="col-12 col-md-10 mt-1">
                    <div class="row">
                        <div class="col-6 col-md-5">
                            <div class="d-md-none">
                                <img src="{% static 'images/pub_date.png' %}" width="15px" height="auto" alt="Published date">
                                <strong>{{ job.posted_date_details }}</strong>
                            </div>
                            <div class="d-none d-md-block">
                                Posted:
                                <strong>{{ job.posted_date_details }}</strong>
                            </div>
                        </div>
                        <div class="col-6 col-md-5">
                            <div class="d-md-none">
                                <img src="{% static 'images/building.png' %}" width="17px" height="auto" alt="Company">
                                <strong>{{ job.company }}</strong>
                            </div>
                            <div class="d-none d-md-block">
                                Company:
                                <strong>{{ job.company }}</strong>
                            </div>
                        </div>
                    </div>
                    <div class="row mb-1">
                        <div class="col-6 col-md-5">
                            {% if job.end_date %}
                                <div class="d-md-none">
                                    <img src="{% static 'images/end_date.png' %}" width="17px" height="auto" alt="End date">
                                    <strong>{{ job.end_date }}</strong>
                                </div>
                                <div class="d-none d-md-block">
                                    Due date:
                                    <strong>{{ job.end_date }}</strong>
                                </div>
                            {% endif %}
                        </div>
                        <div class="col-6 col-md-5">
                            {% if job.get_locations %}
                                <div class="d-md-none">
                                    <img src="{% static 'images/location.png' %}" width="14px" height="auto" alt="Location">
                                    <strong>{{ job.get_locations }}</strong>
                                </div>
                                <div class="d-none d-md-block">
                                    Location:
                                    <strong>{{ job.get_locations }}</strong>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-2 text-center text-lg-right mb-1 mb-md-0">
                    <a href="{% url 'job_scraper:apply' job.id job.get_title_slug %}" class="btn btn-outline-success btn-sm" target="_blank" rel="nofollow"><strong>Apply!</strong></a>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col job-description mb-5">
            <p>{{ job.description |safe }}</p>
        </div>
    </div>

{% endblock %}

job_scraper/templates/locations.html
{% extends "base.html" %}
{% load static %}
{% load search_tags %}


{% block content %}

<div class="row mt-5 mb-4">
    <div class="col text-center">
        <h2>
            <strong>
                Have a look at all our locations and their jobs
            </strong>
        </h2>
    </div>
</div>

<div class="row justify-content-center align-items-center">
    {% for location in locations_list %}
    {% if forloop.counter0|divisibleby:5 %}
</div>
<div class="row justify-content-center align-items-center mt-xl-4">
    {% endif %}

    <div class="col-auto text-center mt-2 mt-xl-0">
        <div>
            <a href="/jobs-in-{{ location.cities__name }}">
                <button type="button" class="location-label mr-lg-3">
                    <div class="pt-2 pl-2 pr-1">
                <h5>    {{ location.cities__name }}  <span class="ml-lg-1 badge badge-success">
                    {{ location.num_jobs }} </span> </h5>
                        </div>
                </button>
            </a>
        </div>

    </div>
    {% endfor %}

</div>

<div class="pt-lg-5 pb-lg-5"></div>

{% endblock %}